{{- if or .Values.customConfig (include "openvoxdb.readDatabaseEnabled" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvoxdb.fullname" . }}-config
  labels:
    {{- include "openvoxdb.labels" . | nindent 4 }}
data:
  {{- if include "openvoxdb.readDatabaseEnabled" . }}
  read-database.conf: |
    read-database: {
      subname: "//"${OPENVOXDB_POSTGRES_HOSTNAME}":"${OPENVOXDB_POSTGRES_PORT}"/"${OPENVOXDB_POSTGRES_DATABASE}
      username: ${OPENVOXDB_POSTGRES_READ_USER}
      password: ${OPENVOXDB_POSTGRES_READ_PASSWORD}
    }
  {{- end }}
  {{- range $filename, $content := .Values.customConfig }}
  {{- if or (contains "/" $filename) (not (hasSuffix ".conf" $filename)) }}
  {{- fail "customConfig keys must be conf.d filenames ending in .conf without slashes" }}
  {{- end }}
  {{ $filename | quote }}: {{ $content | quote }}
  {{- end }}
{{- end }}
