{{- if .Values.postgresql.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvoxdb.postgresqlFullname" . }}
  labels:
    {{- include "openvoxdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "openvoxdb.postgresqlSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.shared.port }}
      targetPort: postgresql
{{- end }}
