{{- if and .Values.postgresql.internal.enabled (not .Values.postgresql.shared.existingSecret) }}
{{- $secretName := include "openvoxdb.postgresqlSecretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "openvoxdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  {{ .Values.postgresql.shared.usernameKey }}: {{ .Values.postgresql.shared.username | b64enc | quote }}
  {{- if .Values.postgresql.internal.password }}
  {{ .Values.postgresql.shared.passwordKey }}: {{ .Values.postgresql.internal.password | b64enc | quote }}
  {{- else if and $existing (hasKey $existing.data .Values.postgresql.shared.passwordKey) }}
  {{ .Values.postgresql.shared.passwordKey }}: {{ index $existing.data .Values.postgresql.shared.passwordKey | quote }}
  {{- else }}
  {{ .Values.postgresql.shared.passwordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
